### ISSUE TITLE
Avoiding Windows

### ISSUE THREAD

**Issue by Mierdin** [Juniper/vqfx10k-vagrant#17]
What is the reason for avoiding Windows hosts, such as in https://github.com/Juniper/vqfx10k-vagrant/blob/master/full-2qfx-4srv-evpnvxlan/Vagrantfile#L115 ?

**Comment by trmccart** [comment]
Good question. I believe it was just a matter of testing. When this was originally built, we weren't using windows machines for development. 

Interested in giving it a try? Would love some feedback and/or fixes.
