### ISSUE TITLE
light-ipfabric-2S-3L example no ansible.conf; therefore, no merging "role/x/defaults" with "host_vars". 

### ISSUE THREAD

**Issue by icjnpr** [Juniper/vqfx10k-vagrant#4]
ansible.conf is missing with:

[defaults]
hash_behaviour=merge
inventory = .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory

because of that, e.g.: "underlay.network_size" in the underlay_bgp role fails (with 'dict object' has no attribute not found)

**Comment by dgarros** [comment]
Hi @icjnpr 
Good catch, I uploaded the ansible.cfg file 
Please let me know if it's working now
Thanks
Damien

**Comment by icjnpr** [comment]
Yeap, all good.

Best regards,
Iddo
